import type { CSpellSettings } from "cspell";

const config: CSpellSettings = {
  version: "0.2",
  language: "en",
  files: ["**/*.{ts,tsx,js,jsx,mjs,cjs}", "**/*.{json,md,mdx}", "**/*.{css,scss,sass}"],
  ignorePaths: [
    "node_modules/**",
    ".next/**",
    "dist/**",
    "build/**",
    "out/**",
    "coverage/**",
    ".git/**",
    "pnpm-lock.yaml",
    "package-lock.json",
    "yarn.lock",
    "**/*.min.*",
    "public/**",
    "drizzle/**",
  ],
  dictionaries: ["typescript", "node", "npm", "css", "html", "bash", "project-words"],
  words: [
    "nextjs",
    "nextauth",
    "tailwindcss",
    "drizzle",
    "zod",
    "shadcn",
    "radix",
    "lucia",
    "tanstack",
    "jotai",
    "zustand",
    "postgres",
    "postgresql",
    "neon",
    "prisma",
    "imagekit",
    "cloudinary",
    "nodemailer",
    "qstash",
    "upstash",
    "vercel",
    "turbopack",
    "comicwise",
    "manhua",
    "manhwa",
    "webtoon",
    "webp",
    "avif",
    "signup",
    "signin",
    "middleware",
    "optimizations",
    "unstable",
    "readonly",
    "typeof",
    "keyof",
    "satisfies",
    "suspense",
    "prefetch",
    "preload",
    "hydration",
    "revalidate",
    "refetch",
    "dropdown",
    "popover",
    "tooltip",
    "breadcrumb",
    "navbar",
    "sidebar",
    "checkbox",
    "hiatus",
    "bookmarked",
    "unbookmark",
  ],
  ignoreRegExpList: [
    "/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi",
    "/[0-9a-fA-F]{3,8}/g",
    "/https?:\\/\\/[^\\s]+/g",
    "/[a-zA-Z0-9._%+-]+[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}/g",
    "/\\.\\/([\\/\\w\\-\\.]+)/g",
    "/import\\s+.*?from\\s+['\"].*?['\"]/g",
    '/data:[^;]*;base64,[^"]+/g',
    "/\\b[a-zA-Z0-9]{20,}\\b/g",
  ],
  caseSensitive: false,
  allowCompoundWords: true,
  dictionaryDefinitions: [
    {
      name: "project-words",
      path: "./project-words.txt",
      description: "Words used in this project",
      addWords: true,
    },
  ],
  languageSettings: [
    {
      languageId: "typescript,javascript,typescriptreact,javascriptreact",
      ignoreRegExpList: ["/import\\s+.*?from\\s+['\"].*?['\"]/g", "/require\\(['\"].*?['\"]\\)/g"],
    },
  ],
};

export default config;
